import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { ensureFacebookDestination, scheduleAndVerify } from './publishing-guards.js';
const account={pageId:'123',pageName:'Fixture Page',destinationGroupLabel:'Publish to',destinationLabel:'Fixture Page Facebook',successText:'Post scheduled',successLinkLabel:'View scheduled post'};
async function fixture(t,html){const browser=await chromium.launch({headless:true,...(process.env.META_TEST_BROWSER?{executablePath:process.env.META_TEST_BROWSER}:{})});t.after(()=>browser.close());const context=await browser.newContext();await context.route('**/*',route=>route.fulfill({contentType:'text/html',body:html}));const page=await context.newPage();await page.goto('https://business.facebook.com/latest/composer/?asset_id=123');return page;}
const controls='<fieldset aria-label="Publish to"><label><input type="checkbox">Fixture Page Facebook</label><label><input type="checkbox" checked>Instagram</label><label><input type="checkbox" checked>Other Facebook</label></fieldset>';
test('browser destination selection leaves exactly the intended Facebook Page checked',async t=>{const page=await fixture(t,controls);await ensureFacebookDestination(page,account);assert.equal(await page.getByRole('checkbox',{name:'Fixture Page Facebook',exact:true}).isChecked(),true);assert.equal(await page.locator('input:checked').count(),1);await page.goto('https://business.facebook.com/latest/composer/?asset_id=999');await assert.rejects(ensureFacebookDestination(page,account),/identity/);});
test('browser receipt appears after a persisted intent and verifies the post identity',async t=>{const page=await fixture(t,controls+'<button onclick="document.body.insertAdjacentHTML(\'beforeend\',\'<p>Post scheduled</p><a href=https://www.facebook.com/fixture/posts/456>View scheduled post</a>\')">Schedule</button>');let saved=false;const receipt=await scheduleAndVerify(page,account,async()=>{assert.equal(await page.getByText('Post scheduled',{exact:true}).count(),0);saved=true;});assert.equal(saved,true);assert.equal(receipt.postId,'456');await assert.rejects(scheduleAndVerify(page,account,()=>assert.fail()),/stale/);});
test('a restriction stops before the browser can submit',async t=>{const page=await fixture(t,controls+'<p>You cannot access this service</p><button>Schedule</button>');await assert.rejects(scheduleAndVerify(page,account,()=>assert.fail()),/account action/);});
